/**
 * 七年级上册词汇学习数据
 * 基于人教版教材词汇框架，提供原创学习内容
 * 所有例句和释义均为独立创作，用于教学目的
 */

import type { TextbookWord } from './textbook-vocabulary';

// Unit 1: You and Me 词汇
export const UNIT1_VOCABULARY: Omit<TextbookWord, 'grade' | 'book' | 'unit'>[] = [
  {
    id: '7a_u1_make_friends',
    word: 'make friends',
    phonetic: '',
    definitions: [{ partOfSpeech: 'phrase', meaning: '交朋友', exampleSentence: 'I want to make friends with you.' }],
    examples: ['I want to make friends with you.', 'She likes to make friends at school.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_get_to_know',
    word: 'get to know',
    phonetic: '',
    definitions: [{ partOfSpeech: 'phrase', meaning: '认识；了解', exampleSentence: 'I want to get to know everyone in my class.' }],
    examples: ['I want to get to know everyone in my class.', "Let's get to know each other better."],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_each',
    word: 'each',
    phonetic: '/iːtʃ/',
    definitions: [{ partOfSpeech: 'adj. & pron.', meaning: '每个；各自', exampleSentence: 'Each student has a book.' }],
    examples: ['Each student has a book.', 'They each have different hobbies.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_other',
    word: 'other',
    phonetic: '/ˈʌðə(r)/',
    definitions: [{ partOfSpeech: 'pron.', meaning: '另外的人（或物）', exampleSentence: 'Some students like math, others like English.' }],
    examples: ['Some students like math, others like English.', 'Do you have any other questions?'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_each_other',
    word: 'each other',
    phonetic: '',
    definitions: [{ partOfSpeech: 'phrase', meaning: '互相；彼此', exampleSentence: 'We help each other with homework.' }],
    examples: ['We help each other with homework.', 'They know each other well.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_full',
    word: 'full',
    phonetic: '/fʊl/',
    definitions: [{ partOfSpeech: 'adj.', meaning: '完整的；满的', exampleSentence: 'Please write your full name here.' }],
    examples: ['Please write your full name here.', 'The classroom is full of students.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_full_name',
    word: 'full name',
    phonetic: '',
    definitions: [{ partOfSpeech: 'n.', meaning: '全名', exampleSentence: 'My full name is Li Ming.' }],
    examples: ['My full name is Li Ming.', 'What is your full name?'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_grade',
    word: 'grade',
    phonetic: '/ɡreɪd/',
    definitions: [{ partOfSpeech: 'n.', meaning: '年级；等级', exampleSentence: 'I am in Grade 7.' }],
    examples: ['I am in Grade 7.', 'What grade are you in?'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_last_name',
    word: 'last name',
    phonetic: '',
    definitions: [{ partOfSpeech: 'n.', meaning: '姓氏', exampleSentence: 'My last name is Wang.' }],
    examples: ['My last name is Wang.', 'What is your last name?'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_classmate',
    word: 'classmate',
    phonetic: '/ˈklɑːsmeɪt/',
    definitions: [{ partOfSpeech: 'n.', meaning: '同班同学', exampleSentence: 'She is my classmate.' }],
    examples: ['She is my classmate.', 'I have many classmates in my class.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_class_teacher',
    word: 'class teacher',
    phonetic: '',
    definitions: [{ partOfSpeech: 'n.', meaning: '班主任', exampleSentence: 'Our class teacher is very kind.' }],
    examples: ['Our class teacher is very kind.', 'The class teacher teaches us English.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_first_name',
    word: 'first name',
    phonetic: '',
    definitions: [{ partOfSpeech: 'n.', meaning: '名字', exampleSentence: 'My first name is Tom.' }],
    examples: ['My first name is Tom.', 'What is your first name?'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_mistake',
    word: 'mistake',
    phonetic: '/mɪˈsteɪk/',
    definitions: [{ partOfSpeech: 'n.', meaning: '错误；失误', exampleSentence: 'Everyone makes mistakes.' }],
    examples: ['Everyone makes mistakes.', 'I made a mistake in my homework.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_country',
    word: 'country',
    phonetic: '/ˈkʌntri/',
    definitions: [{ partOfSpeech: 'n.', meaning: '国家', exampleSentence: 'China is a big country.' }],
    examples: ['China is a big country.', 'What country are you from?'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_same',
    word: 'same',
    phonetic: '/seɪm/',
    definitions: [{ partOfSpeech: 'adj.', meaning: '相同的', exampleSentence: 'We are in the same class.' }],
    examples: ['We are in the same class.', 'They have the same hobby.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_twin',
    word: 'twin',
    phonetic: '/twɪn/',
    definitions: [{ partOfSpeech: 'n.', meaning: '双胞胎之一', exampleSentence: 'She has a twin sister.' }],
    examples: ['She has a twin sister.', 'The twins look very similar.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_both',
    word: 'both',
    phonetic: '/bəʊθ/',
    definitions: [{ partOfSpeech: 'adj. & pron.', meaning: '两个；两个都', exampleSentence: 'Both of them are students.' }],
    examples: ['Both of them are students.', 'I like both apples and oranges.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_band',
    word: 'band',
    phonetic: '/bænd/',
    definitions: [{ partOfSpeech: 'n.', meaning: '乐队', exampleSentence: 'He plays in a band.' }],
    examples: ['He plays in a band.', 'The band is very popular.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_pot',
    word: 'pot',
    phonetic: '/pɒt/',
    definitions: [{ partOfSpeech: 'n.', meaning: '锅', exampleSentence: 'Put the vegetables in the pot.' }],
    examples: ['Put the vegetables in the pot.', 'The pot is on the stove.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_a_lot',
    word: 'a lot',
    phonetic: '',
    definitions: [{ partOfSpeech: 'phrase', meaning: '很；非常', exampleSentence: 'I like English a lot.' }],
    examples: ['I like English a lot.', 'She helps me a lot.'],
    difficulty: 'basic',
    frequency: 'high',
  },
  {
    id: '7a_u1_guitar',
    word: 'guitar',
    phonetic: '/ɡɪˈtɑː(r)/',
    definitions: [{ partOfSpeech: 'n.', meaning: '吉他', exampleSentence: 'He can play the guitar.' }],
    examples: ['He can play the guitar.', 'I want to learn to play the guitar.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_tennis',
    word: 'tennis',
    phonetic: '/ˈtenɪs/',
    definitions: [{ partOfSpeech: 'n.', meaning: '网球', exampleSentence: 'Do you like playing tennis?' }],
    examples: ['Do you like playing tennis?', 'Tennis is a popular sport.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_post',
    word: 'post',
    phonetic: '/pəʊst/',
    definitions: [{ partOfSpeech: 'n. & v.', meaning: '帖子；邮政；邮寄；发布', exampleSentence: 'I will post a message online.' }],
    examples: ['I will post a message online.', 'She posted a photo on social media.'],
    difficulty: 'basic',
    frequency: 'medium',
  },
  {
    id: '7a_u1_even',
    word: 'even',
    phonetic: '/ˈiːvn/',
    definitions: [{ partOfSpeech: 'adv.', meaning: '甚至；连；愈加', exampleSentence: 'He can even speak three languages.' }],
    examples: ['He can even speak three languages.', 'She is even taller than her brother.'],
    difficulty: 'intermediate',
    frequency: 'high',
  },
  {
    id: '7a_u1_would',
    word: 'would',
    phonetic: '/wʊd/',
    definitions: [{ partOfSpeech: 'modal v.', meaning: '想（用于礼貌地邀请或向某人提供某物）；将会', exampleSentence: 'Would you like some tea?' }],
    examples: ['Would you like some tea?', 'I would like to help you.'],
    difficulty: 'intermediate',
    frequency: 'high',
  },
  {
    id: '7a_u1_would_like_to',
    word: "would ('d) like to",
    phonetic: '',
    definitions: [{ partOfSpeech: 'phrase', meaning: '表示意愿，喜欢', exampleSentence: "I'd like to join the club." }],
    examples: ["I'd like to join the club.", "Would you like to come with us?"],
    difficulty: 'intermediate',
    frequency: 'high',
  },
  {
    id: '7a_u1_information',
    word: 'information',
    phonetic: '/ˌɪnfəˈmeɪʃn/',
    definitions: [{ partOfSpeech: 'n.', meaning: '信息；消息', exampleSentence: 'Can you give me some information?' }],
    examples: ['Can you give me some information?', 'This book has a lot of useful information.'],
    difficulty: 'intermediate',
    frequency: 'high',
  },
  {
    id: '7a_u1_hobby',
    word: 'hobby',
    phonetic: '/ˈhɒbi/',
    definitions: [{ partOfSpeech: 'n.', meaning: '业余爱好', exampleSentence: 'My hobby is reading books.' }],
    examples: ['My hobby is reading books.', 'What is your hobby?'],
    difficulty: 'basic',
    frequency: 'high',
  },
];

// 由于内容较多，这里先提供Unit 1的完整示例
// 其他单元将采用类似格式继续添加

export function getCompleteVocabularyForUnit(unit: number): Omit<TextbookWord, 'grade' | 'book' | 'unit'>[] {
  switch (unit) {
    case 1:
      return UNIT1_VOCABULARY;
    // 其他单元将在后续添加
    default:
      return [];
  }
}
